#
# Environment specific definitions
#

#
# response time endpoints
#

CLIENT_LANDING:
 title: 'Client'
 url: <%= "#{ENV['CLIENT_SERVICE']}/" %>
 id: 'client-landing-time'

#
# healthcheck endpoints
#

AVAILABILITY_SERVICE:
 title: 'Availability'
 url: <%= "#{ENV['AVAILABILITY_SERVICE']}/healthcheck" %>
 id: 'availability-service'

CLIENT_SERVICE:
 title: 'Client'
 url: <%= "#{ENV['CLIENT_SERVICE']}/healthcheck" %>
 id: 'client-service'

CITATIONS_SERVICE:
  title: 'Citations'
  url: <%= "#{ENV['CITATIONS_SERVICE']}/healthcheck" %>
  id: 'citations-service'

COLLECTIONS_SERVICE:
 title: 'Collections'
 url: <%= "#{ENV['COLLECTIONS_SERVICE']}/healthcheck" %>
 id: 'collections-service'

ILS_SERVICE:
  title: 'ILS Connect'
  url: <%= "#{ENV['ILS_SERVICE']}/healthcheck" %>
  id: 'ils-service'

PDA_SERVICE:
 title: 'PDA'
 url: <%= "#{ENV['PDA_SERVICE']}/healthcheck" %>
 id: 'ils-service'

SEARCH_SERVICE:
 title: 'Search'
 url: <%= "#{ENV['SEARCH_SERVICE']}/healthcheck" %>
 id: 'search-service'

SHELF_BROWSE_SERVICE:
 title: 'Shelf Browse'
 url: <%= "#{ENV['SHELF_BROWSE_SERVICE']}/healthcheck" %>
 id: 'shelf-browse-service'

SUGGESTER_SERVICE:
  title: 'Suggester'
  url: <%= "#{ENV['SUGGESTER_SERVICE']}/healthcheck" %>
  id: 'suggester-service'

SOLR_MASTER:
 title: 'SOLR Master'
 url: <%= "#{ENV['SOLR_MASTER']}/solr/admin/info/system" %>
 id: 'solr-master'

SOLR_REPLICA_0:
 title: 'SOLR Replica-0'
 url: <%= "#{ENV['SOLR_REPLICA_0']}/solr/admin/info/system" %>
 id: 'solr-replica-0'

SOLR_REPLICA_1:
 title: 'SOLR Replica-1'
 url: <%= "#{ENV['SOLR_REPLICA_1']}/solr/admin/info/system" %>
 id: 'solr-replica-1'

EDS_ARTICLES_POOL_SERVICE:
 title: 'EDS Articles'
 url: <%= "#{ENV['EDS_ARTICLES_POOL_SERVICE']}/healthcheck" %>
 id: 'eds-articles-pool-service'

JMRL_POOL_SERVICE:
  title: 'JMRL'
  url: <%= "#{ENV['JMRL_POOL_SERVICE']}/healthcheck" %>
  id: 'jmrl-pool-service'

SOLR_HATHITRUST_POOL_SERVICE:
 title: 'HathiTrust'
 url: <%= "#{ENV['SOLR_HATHITRUST_POOL_SERVICE']}/healthcheck" %>
 id: 'solr-hathitrust-pool-service'

SOLR_IMAGES_POOL_SERVICE:
 title: 'Images'
 url: <%= "#{ENV['SOLR_IMAGES_POOL_SERVICE']}/healthcheck" %>
 id: 'solr-images-pool-service'

SOLR_UVALIBRARY_POOL_SERVICE:
 title: 'UVa Library'
 url: <%= "#{ENV['SOLR_UVALIBRARY_POOL_SERVICE']}/healthcheck" %>
 id: 'solr-uva-library-pool-service'

WORLDCAT_POOL_SERVICE:
  title: 'WorldCat'
  url: <%= "#{ENV['WORLDCAT_POOL_SERVICE']}/healthcheck" %>
  id: 'worldcat-pool-service'

INGEST_GENERAL:
 last_n_minutes: '15'
 last_n_hours: '24'

#
# inbound queues
#

INGEST_DYNAMIC_MARC_CONVERT_QUEUE_IN:
  title: 'Dynmc MRC'
  queue: <%= "virgo4-ingest-dynamic-marc-convert-#{ENV[ 'ENVIRONMENT' ]}" %>
  metric: 'NumberOfMessagesSent'
  id: 'dynamic-marc-convert-in-count'

INGEST_DYNAMIC_MARC_CONVERT_QUEUE_OUT:
  title: ''
  queue: <%= "virgo4-ingest-dynamic-marc-convert-#{ENV[ 'ENVIRONMENT' ]}" %>
  metric: 'NumberOfMessagesDeleted'
  id: 'dynamic-marc-convert-out-count'

INGEST_HATHI_MARC_CONVERT_QUEUE_IN:
 title: 'Hathi MRC'
 queue: <%= "virgo4-ingest-hathi-marc-convert-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesSent'
 id: 'hathi-marc-convert-in-count'

INGEST_HATHI_MARC_CONVERT_QUEUE_OUT:
 title: ''
 queue: <%= "virgo4-ingest-hathi-marc-convert-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesDeleted'
 id: 'hathi-marc-convert-out-count'

INGEST_SIRSI_MARC_CONVERT_QUEUE_IN:
  title: 'Sirsi MRC'
  queue: <%= "virgo4-ingest-sirsi-marc-convert-#{ENV[ 'ENVIRONMENT' ]}" %>
  metric: 'NumberOfMessagesSent'
  id: 'sirsi-marc-convert-in-count'

INGEST_SIRSI_MARC_CONVERT_QUEUE_OUT:
  title: ''
  queue: <%= "virgo4-ingest-sirsi-marc-convert-#{ENV[ 'ENVIRONMENT' ]}" %>
  metric: 'NumberOfMessagesDeleted'
  id: 'sirsi-marc-convert-out-count'

#
# pipeline queues
#

INGEST_IMAGE_TRACKSYS_ENRICH_QUEUE_IN:
 title: 'Img TrkSys'
 queue: <%= "virgo4-ingest-image-tracksys-enrich-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesSent'
 id: 'image-tracksys-enrich-in-count'

INGEST_IMAGE_TRACKSYS_ENRICH_QUEUE_OUT:
 title: ''
 queue: <%= "virgo4-ingest-image-tracksys-enrich-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesDeleted'
 id: 'image-tracksys-enrich-out-count'

INGEST_SIRSI_TRACKSYS_ENRICH_QUEUE_IN:
 title: 'Sirsi TrkSys'
 queue: <%= "virgo4-ingest-sirsi-tracksys-enrich-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesSent'
 id: 'sirsi-tracksys-enrich-in-count'

INGEST_SIRSI_TRACKSYS_ENRICH_QUEUE_OUT:
 title: ''
 queue: <%= "virgo4-ingest-sirsi-tracksys-enrich-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesDeleted'
 id: 'sirsi-tracksys-enrich-out-count'

INGEST_DEFAULT_SOLR_UPDATE_QUEUE_IN:
 title: 'Def SOLR'
 queue: <%= "virgo4-ingest-default-solr-update-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesSent'
 id: 'default-solr-update-in-count'

INGEST_DEFAULT_SOLR_UPDATE_QUEUE_OUT:
 title: ''
 queue: <%= "virgo4-ingest-default-solr-update-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesDeleted'
 id: 'default-solr-update-out-count'

INGEST_IMAGE_SOLR_UPDATE_QUEUE_IN:
  title: 'Img SOLR'
  queue: <%= "virgo4-ingest-image-solr-update-#{ENV[ 'ENVIRONMENT' ]}" %>
  metric: 'NumberOfMessagesSent'
  id: 'image-solr-update-in-count'

INGEST_IMAGE_SOLR_UPDATE_QUEUE_OUT:
  title: ''
  queue: <%= "virgo4-ingest-image-solr-update-#{ENV[ 'ENVIRONMENT' ]}" %>
  metric: 'NumberOfMessagesDeleted'
  id: 'image-solr-update-out-count'

INGEST_CACHE_QUEUE_IN:
 title: 'Cache'
 queue: <%= "virgo4-ingest-cache-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesSent'
 id: 'cache-in-count'

INGEST_CACHE_QUEUE_OUT:
 title: ''
 queue: <%= "virgo4-ingest-cache-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesDeleted'
 id: 'cache-out-count'

INGEST_IMAGE_DOC_QUEUE_IN:
  title: 'Image Doc'
  queue: <%= "virgo4-ingest-image-solr-update-#{ENV[ 'ENVIRONMENT' ]}" %>
  metric: 'NumberOfMessagesSent'
  id: 'image-doc-in-count'

INGEST_IMAGE_DOC_QUEUE_OUT:
  title: ''
  queue: <%= "virgo4-ingest-image-solr-update-#{ENV[ 'ENVIRONMENT' ]}" %>
  metric: 'NumberOfMessagesDeleted'
  id: 'image-doc-out-count'

#
# custom metrics
#

SEARCH_COUNT_5M:
 title: 'Last 5 min'
 metric: <%= "total-search-count-#{ENV[ 'ENVIRONMENT' ]}" %>
 last_n_minutes: '5'
 scale: '500'
 id: 'total-search-count-5-m'

SEARCH_COUNT_15M:
 title: 'Last 15 min'
 metric: <%= "total-search-count-#{ENV[ 'ENVIRONMENT' ]}" %>
 last_n_minutes: '15'
 scale: '1500'
 id: 'total-search-count-15-m'

SEARCH_COUNT_60M:
 title: 'Last hour'
 metric: <%= "total-search-count-#{ENV[ 'ENVIRONMENT' ]}" %>
 last_n_minutes: '60'
 scale: '10000'
 id: 'total-search-count-60-m'

SEARCH_COUNT_24H:
 title: 'Last 24 hrs'
 metric: <%= "total-search-count-#{ENV[ 'ENVIRONMENT' ]}" %>
 last_n_minutes: '1440'
 scale: '100000'
 id: 'total-search-count-24-h'

#
# end of file
#
