#
# Environment specific definitions
#

#
# the endpoints to inspect
#

CLIENT_LANDING:
 title: 'Client'
 url: <%= "#{ENV['CLIENT_SERVICE']}/" %>
 id: 'client-landing-time'

CLIENT_SERVICE:
 title: 'Client'
 url: <%= "#{ENV['CLIENT_SERVICE']}/healthcheck" %>
 id: 'client-service'

SEARCH_SERVICE:
 title: 'Search'
 url: <%= "#{ENV['SEARCH_SERVICE']}/healthcheck" %>
 id: 'search-service'

SOLR_MASTER:
 title: 'SOLR Master'
 url: <%= "#{ENV['SOLR_MASTER']}/solr/admin/info/system" %>
 id: 'solr-master'

SOLR_REPLICA_0:
 title: 'SOLR Replica-0'
 url: <%= "#{ENV['SOLR_REPLICA_0']}/solr/admin/info/system" %>
 id: 'solr-replica-0'

SOLR_REPLICA_1:
 title: 'SOLR Replica-1'
 url: <%= "#{ENV['SOLR_REPLICA_1']}/solr/admin/info/system" %>
 id: 'solr-replica-1'

EDS_ARTICLES_POOL_SERVICE:
 title: 'EDS Articles'
 url: <%= "#{ENV['EDS_ARTICLES_POOL_SERVICE']}/healthcheck" %>
 id: 'eds-articles-pool-service'

SOLR_ARCHIVAL_POOL_SERVICE:
  title: 'SOLR Archival'
  url: <%= "#{ENV['SOLR_ARCHIVAL_POOL_SERVICE']}/healthcheck" %>
  id: 'solr-archival-pool-service'

SOLR_CATALOG_POOL_SERVICE:
 title: 'SOLR Catalog'
 url: <%= "#{ENV['SOLR_CATALOG_POOL_SERVICE']}/healthcheck" %>
 id: 'solr-catalog-pool-service'

SOLR_CATALOG_BROAD_POOL_SERVICE:
 title: 'SOLR Catalog Broad'
 url: <%= "#{ENV['SOLR_CATALOG_BROAD_POOL_SERVICE']}/healthcheck" %>
 id: 'solr-catalog-broad-pool-service'

SOLR_MUSIC_RECORDINGS_POOL_SERVICE:
 title: 'SOLR Music Recordings'
 url: <%= "#{ENV['SOLR_MUSIC_RECORDINGS_POOL_SERVICE']}/healthcheck" %>
 id: 'solr-music-rec-pool-service'

SOLR_MUSICAL_SCORES_POOL_SERVICE:
  title: 'SOLR Musical Scores'
  url: <%= "#{ENV['SOLR_MUSICAL_SCORES_POOL_SERVICE']}/healthcheck" %>
  id: 'solr-musical-score-pool-service'

SOLR_RAREBOOKS_POOL_SERVICE:
  title: 'SOLR Rare Books'
  url: <%= "#{ENV['SOLR_RAREBOOKS_POOL_SERVICE']}/healthcheck" %>
  id: 'solr-rarebooks-pool-service'

SOLR_SERIALS_POOL_SERVICE:
  title: 'SOLR Serials'
  url: <%= "#{ENV['SOLR_SERIALS_POOL_SERVICE']}/healthcheck" %>
  id: 'solr-serials-pool-service'

SOLR_SOUND_RECORDINGS_POOL_SERVICE:
 title: 'SOLR Sound Recordings'
 url: <%= "#{ENV['SOLR_MUSIC_RECORDINGS_POOL_SERVICE']}/healthcheck" %>
 id: 'solr-sound-rec-pool-service'

SOLR_VIDEO_POOL_SERVICE:
 title: 'SOLR Video'
 url: <%= "#{ENV['SOLR_VIDEO_POOL_SERVICE']}/healthcheck" %>
 id: 'solr-video-pool-service'

INGEST_GENERAL:
 last_n_minutes: '15'
 last_n_hours: '24'

INGEST_DYNAMIC_MARC_CONVERT_QUEUE_IN:
  title: 'Dynmc MRC'
  queue: <%= "virgo4-ingest-dynamic-marc-convert-#{ENV[ 'ENVIRONMENT' ]}" %>
  metric: 'NumberOfMessagesSent'
  id: 'dynamic-marc-convert-in-count'

INGEST_DYNAMIC_MARC_CONVERT_QUEUE_OUT:
  title: ''
  queue: <%= "virgo4-ingest-dynamic-marc-convert-#{ENV[ 'ENVIRONMENT' ]}" %>
  metric: 'NumberOfMessagesDeleted'
  id: 'dynamic-marc-convert-out-count'

INGEST_HATHI_MARC_CONVERT_QUEUE_IN:
 title: 'Hathi MRC'
 queue: <%= "virgo4-ingest-hathi-marc-convert-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesSent'
 id: 'hathi-marc-convert-in-count'

INGEST_HATHI_MARC_CONVERT_QUEUE_OUT:
 title: ''
 queue: <%= "virgo4-ingest-hathi-marc-convert-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesDeleted'
 id: 'hathi-marc-convert-out-count'

INGEST_SIRSI_MARC_CONVERT_QUEUE_IN:
  title: 'Sirsi MRC'
  queue: <%= "virgo4-ingest-sirsi-marc-convert-#{ENV[ 'ENVIRONMENT' ]}" %>
  metric: 'NumberOfMessagesSent'
  id: 'sirsi-marc-convert-in-count'

INGEST_SIRSI_MARC_CONVERT_QUEUE_OUT:
  title: ''
  queue: <%= "virgo4-ingest-sirsi-marc-convert-#{ENV[ 'ENVIRONMENT' ]}" %>
  metric: 'NumberOfMessagesDeleted'
  id: 'sirsi-marc-convert-out-count'

INGEST_TRACKSYS_ENRICH_QUEUE_IN:
 title: 'TrackSys'
 queue: <%= "virgo4-ingest-sirsi-tracksys-enrich-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesSent'
 id: 'tracksys-enrich-in-count'

INGEST_TRACKSYS_ENRICH_QUEUE_OUT:
 title: ''
 queue: <%= "virgo4-ingest-sirsi-tracksys-enrich-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesDeleted'
 id: 'tracksys-enrich-out-count'

INGEST_SOLR_UPDATE_QUEUE_IN:
 title: 'SOLR add'
 queue: <%= "virgo4-ingest-solr-update-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesSent'
 id: 'solr-update-in-count'

INGEST_SOLR_UPDATE_QUEUE_OUT:
 title: ''
 queue: <%= "virgo4-ingest-solr-update-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesDeleted'
 id: 'solr-update-out-count'

INGEST_CACHE_QUEUE_IN:
 title: 'Cache'
 queue: <%= "virgo4-ingest-cache-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesSent'
 id: 'cache-in-count'

INGEST_CACHE_QUEUE_OUT:
 title: ''
 queue: <%= "virgo4-ingest-cache-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesDeleted'
 id: 'cache-out-count'

#
# end of file
#