#
# Environment specific definitions
#

#
# response time endpoints
#

CLIENT_LANDING:
 title: 'Client'
 url: <%= "#{ENV['CLIENT_SERVICE']}/" %>
 id: 'client-landing-time'

#
# healthcheck endpoints
#

CLIENT_SERVICE:
 title: 'Client'
 url: <%= "#{ENV['CLIENT_SERVICE']}/healthcheck" %>
 id: 'client-service'

CITATIONS_SERVICE:
  title: 'Citations'
  url: <%= "#{ENV['CITATIONS_SERVICE']}/healthcheck" %>
  id: 'citations-service'

DIGITAL_CONTENT_SERVICE:
 title: 'Digital Content'
 url: <%= "#{ENV['DIGITAL_CONTENT_SERVICE']}/healthcheck" %>
 id: 'digital-content-service'

ILS_SERVICE:
  title: 'ILS Connect'
  url: <%= "#{ENV['ILS_SERVICE']}/healthcheck" %>
  id: 'ils-service'

PDA_SERVICE:
 title: 'PDA'
 url: <%= "#{ENV['PDA_SERVICE']}/healthcheck" %>
 id: 'ils-service'

SEARCH_SERVICE:
 title: 'Search'
 url: <%= "#{ENV['SEARCH_SERVICE']}/healthcheck" %>
 id: 'search-service'

SUGGESTER_SERVICE:
  title: 'Suggester'
  url: <%= "#{ENV['SUGGESTER_SERVICE']}/healthcheck" %>
  id: 'suggester-service'

SOLR_MASTER:
 title: 'SOLR Master'
 url: <%= "#{ENV['SOLR_MASTER']}/solr/admin/info/system" %>
 id: 'solr-master'

SOLR_REPLICA_0:
 title: 'SOLR Replica-0'
 url: <%= "#{ENV['SOLR_REPLICA_0']}/solr/admin/info/system" %>
 id: 'solr-replica-0'

SOLR_REPLICA_1:
 title: 'SOLR Replica-1'
 url: <%= "#{ENV['SOLR_REPLICA_1']}/solr/admin/info/system" %>
 id: 'solr-replica-1'

EDS_ARTICLES_POOL_SERVICE:
 title: 'EDS Articles'
 url: <%= "#{ENV['EDS_ARTICLES_POOL_SERVICE']}/healthcheck" %>
 id: 'eds-articles-pool-service'

JMRL_POOL_SERVICE:
  title: 'JMRL'
  url: <%= "#{ENV['JMRL_POOL_SERVICE']}/healthcheck" %>
  id: 'jmrl-pool-service'

SOLR_ARCHIVAL_POOL_SERVICE:
  title: 'SOLR Archival'
  url: <%= "#{ENV['SOLR_ARCHIVAL_POOL_SERVICE']}/healthcheck" %>
  id: 'solr-archival-pool-service'

SOLR_CATALOG_POOL_SERVICE:
 title: 'SOLR Catalog'
 url: <%= "#{ENV['SOLR_CATALOG_POOL_SERVICE']}/healthcheck" %>
 id: 'solr-catalog-pool-service'

SOLR_IMAGES_POOL_SERVICE:
 title: 'SOLR Images'
 url: <%= "#{ENV['SOLR_IMAGES_POOL_SERVICE']}/healthcheck" %>
 id: 'solr-images-pool-service'

SOLR_MAPS_POOL_SERVICE:
 title: 'SOLR Maps'
 url: <%= "#{ENV['SOLR_MAPS_POOL_SERVICE']}/healthcheck" %>
 id: 'solr-maps-pool-service'

SOLR_MUSIC_RECORDINGS_POOL_SERVICE:
 title: 'SOLR Music Recordings'
 url: <%= "#{ENV['SOLR_MUSIC_RECORDINGS_POOL_SERVICE']}/healthcheck" %>
 id: 'solr-music-rec-pool-service'

SOLR_MUSICAL_SCORES_POOL_SERVICE:
  title: 'SOLR Musical Scores'
  url: <%= "#{ENV['SOLR_MUSICAL_SCORES_POOL_SERVICE']}/healthcheck" %>
  id: 'solr-musical-score-pool-service'

SOLR_SERIALS_POOL_SERVICE:
  title: 'SOLR Serials'
  url: <%= "#{ENV['SOLR_SERIALS_POOL_SERVICE']}/healthcheck" %>
  id: 'solr-serials-pool-service'

SOLR_SOUND_RECORDINGS_POOL_SERVICE:
 title: 'SOLR Sound Recordings'
 url: <%= "#{ENV['SOLR_MUSIC_RECORDINGS_POOL_SERVICE']}/healthcheck" %>
 id: 'solr-sound-rec-pool-service'

SOLR_THESIS_POOL_SERVICE:
  title: 'SOLR Thesis'
  url: <%= "#{ENV['SOLR_THESIS_POOL_SERVICE']}/healthcheck" %>
  id: 'solr-thesis-pool-service'

SOLR_VIDEO_POOL_SERVICE:
 title: 'SOLR Video'
 url: <%= "#{ENV['SOLR_VIDEO_POOL_SERVICE']}/healthcheck" %>
 id: 'solr-video-pool-service'

WORLDCAT_POOL_SERVICE:
  title: 'WorldCat'
  url: <%= "#{ENV['WORLDCAT_POOL_SERVICE']}/healthcheck" %>
  id: 'worldcat-pool-service'

INGEST_GENERAL:
 last_n_minutes: '15'
 last_n_hours: '24'

#
# inbound queues
#

INGEST_DYNAMIC_MARC_CONVERT_QUEUE_IN:
  title: 'Dynmc MRC'
  queue: <%= "virgo4-ingest-dynamic-marc-convert-#{ENV[ 'ENVIRONMENT' ]}" %>
  metric: 'NumberOfMessagesSent'
  id: 'dynamic-marc-convert-in-count'

INGEST_DYNAMIC_MARC_CONVERT_QUEUE_OUT:
  title: ''
  queue: <%= "virgo4-ingest-dynamic-marc-convert-#{ENV[ 'ENVIRONMENT' ]}" %>
  metric: 'NumberOfMessagesDeleted'
  id: 'dynamic-marc-convert-out-count'

INGEST_HATHI_MARC_CONVERT_QUEUE_IN:
 title: 'Hathi MRC'
 queue: <%= "virgo4-ingest-hathi-marc-convert-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesSent'
 id: 'hathi-marc-convert-in-count'

INGEST_HATHI_MARC_CONVERT_QUEUE_OUT:
 title: ''
 queue: <%= "virgo4-ingest-hathi-marc-convert-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesDeleted'
 id: 'hathi-marc-convert-out-count'

INGEST_SIRSI_MARC_CONVERT_QUEUE_IN:
  title: 'Sirsi MRC'
  queue: <%= "virgo4-ingest-sirsi-marc-convert-#{ENV[ 'ENVIRONMENT' ]}" %>
  metric: 'NumberOfMessagesSent'
  id: 'sirsi-marc-convert-in-count'

INGEST_SIRSI_MARC_CONVERT_QUEUE_OUT:
  title: ''
  queue: <%= "virgo4-ingest-sirsi-marc-convert-#{ENV[ 'ENVIRONMENT' ]}" %>
  metric: 'NumberOfMessagesDeleted'
  id: 'sirsi-marc-convert-out-count'

#
# pipeline queues
#

INGEST_IIIF_CACHE_QUEUE_IN:
  title: 'IIF Cache'
  queue: <%= "virgo4-ingest-iiif-manifest-cache-#{ENV[ 'ENVIRONMENT' ]}" %>
  metric: 'NumberOfMessagesSent'
  id: 'iiif-cache-in-count'

INGEST_IIIF_CACHE_QUEUE_OUT:
  title: ''
  queue: <%= "virgo4-ingest-iiif-manifest-cache-#{ENV[ 'ENVIRONMENT' ]}" %>
  metric: 'NumberOfMessagesDeleted'
  id: 'iiif-cache-out-count'

INGEST_TRACKSYS_ENRICH_QUEUE_IN:
 title: 'TrackSys'
 queue: <%= "virgo4-ingest-sirsi-tracksys-enrich-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesSent'
 id: 'tracksys-enrich-in-count'

INGEST_TRACKSYS_ENRICH_QUEUE_OUT:
 title: ''
 queue: <%= "virgo4-ingest-sirsi-tracksys-enrich-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesDeleted'
 id: 'tracksys-enrich-out-count'

INGEST_DEFAULT_SOLR_UPDATE_QUEUE_IN:
 title: 'Def SOLR'
 queue: <%= "virgo4-ingest-default-solr-update-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesSent'
 id: 'default-solr-update-in-count'

INGEST_DEFAULT_SOLR_UPDATE_QUEUE_OUT:
 title: ''
 queue: <%= "virgo4-ingest-default-solr-update-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesDeleted'
 id: 'default-solr-update-out-count'

INGEST_IMAGE_SOLR_UPDATE_QUEUE_IN:
  title: 'Img SOLR'
  queue: <%= "virgo4-ingest-image-solr-update-#{ENV[ 'ENVIRONMENT' ]}" %>
  metric: 'NumberOfMessagesSent'
  id: 'image-solr-update-in-count'

INGEST_IMAGE_SOLR_UPDATE_QUEUE_OUT:
  title: ''
  queue: <%= "virgo4-ingest-image-solr-update-#{ENV[ 'ENVIRONMENT' ]}" %>
  metric: 'NumberOfMessagesDeleted'
  id: 'image-solr-update-out-count'

INGEST_CACHE_QUEUE_IN:
 title: 'Cache'
 queue: <%= "virgo4-ingest-cache-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesSent'
 id: 'cache-in-count'

INGEST_CACHE_QUEUE_OUT:
 title: ''
 queue: <%= "virgo4-ingest-cache-#{ENV[ 'ENVIRONMENT' ]}" %>
 metric: 'NumberOfMessagesDeleted'
 id: 'cache-out-count'

INGEST_IMAGE_DOC_QUEUE_IN:
  title: 'Image Doc'
  queue: <%= "virgo4-ingest-iiif-manifest-cache-#{ENV[ 'ENVIRONMENT' ]}" %>
  metric: 'NumberOfMessagesSent'
  id: 'image-doc-in-count'

INGEST_IMAGE_DOC_QUEUE_OUT:
  title: ''
  queue: <%= "virgo4-ingest-iiif-manifest-cache-#{ENV[ 'ENVIRONMENT' ]}" %>
  metric: 'NumberOfMessagesDeleted'
  id: 'image-doc-out-count'

#
# end of file
#
