#
# Environment specific definitions
#

#
# the endpoints to inspect
#

CLIENT_LANDING:
 title: 'Client'
 url: <%= "#{ENV['CLIENT_SERVICE']}/" %>
 time: 'client-landing-time'

CLIENT_SERVICE:
 title: 'Client'
 url: <%= "#{ENV['CLIENT_SERVICE']}/healthcheck" %>
 id: 'client-service'

SEARCH_SERVICE:
 title: 'Search'
 url: <%= "#{ENV['SEARCH_SERVICE']}/healthcheck" %>
 id: 'search-service'

SOLR_MASTER:
 title: 'SOLR Master'
 url: <%= "#{ENV['SOLR_MASTER']}/solr/admin/info/system" %>
 id: 'solr-master'

SOLR_REPLICA_0:
 title: 'SOLR Replica-0'
 url: <%= "#{ENV['SOLR_REPLICA_0']}/solr/admin/info/system" %>
 id: 'solr-replica-0'

SOLR_REPLICA_1:
 title: 'SOLR Replica-1'
 url: <%= "#{ENV['SOLR_REPLICA_1']}/solr/admin/info/system" %>
 id: 'solr-replica-1'

EDS_ARTICLES_POOL_SERVICE:
  title: 'EDS Articles'
  url: <%= "#{ENV['EDS_ARTICLES_POOL_SERVICE']}/healthcheck" %>
  id: 'eds-articles-pool-service'

SOLR_CATALOG_POOL_SERVICE:
  title: 'SOLR Catalog'
  url: <%= "#{ENV['SOLR_CATALOG_POOL_SERVICE']}/healthcheck" %>
  id: 'solr-catalog-pool-service'

SOLR_CATALOG_BROAD_POOL_SERVICE:
  title: 'SOLR Catalog Broad'
  url: <%= "#{ENV['SOLR_CATALOG_BROAD_POOL_SERVICE']}/healthcheck" %>
  id: 'solr-catalog-broad-pool-service'

SOLR_SERIALS_POOL_SERVICE:
  title: 'SOLR Serials'
  url: <%= "#{ENV['SOLR_SERIALS_POOL_SERVICE']}/healthcheck" %>
  id: 'solr-serials-pool-service'

SOLR_MUSIC_RECORDINGS_POOL_SERVICE:
  title: 'SOLR Music Recordings'
  url: <%= "#{ENV['SOLR_MUSIC_RECORDINGS_POOL_SERVICE']}/healthcheck" %>
  id: 'solr-music-rec-pool-service'

SOLR_SOUND_RECORDINGS_POOL_SERVICE:
  title: 'SOLR Sound Recordings'
  url: <%= "#{ENV['SOLR_MUSIC_RECORDINGS_POOL_SERVICE']}/healthcheck" %>
  id: 'solr-sound-rec-pool-service'

SOLR_VIDEO_POOL_SERVICE:
  title: 'SOLR Video'
  url: <%= "#{ENV['SOLR_VIDEO_POOL_SERVICE']}/healthcheck" %>
  id: 'solr-video-pool-service'

SOLR_MUSICAL_SCORES_POOL_SERVICE:
  title: 'SOLR Musical Scores'
  url: <%= "#{ENV['SOLR_MUSICAL_SCORES_POOL_SERVICE']}/healthcheck" %>
  id: 'solr-musical-score-pool-service'

SOLR_ARCHIVAL_POOL_SERVICE:
  title: 'SOLR Archival'
  url: <%= "#{ENV['SOLR_ARCHIVAL_POOL_SERVICE']}/healthcheck" %>
  id: 'solr-archival-pool-service'

#
# end of file
#